name: Build and Run Container Cowsay

on:
  push:
    branches:
      - main
      
env:
    IMAGE_NAME: wisecow

jobs:
  build-and-run-container:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Set environment variables
        run: |
          COMMIT_HASH=${{ github.sha }}
          LAST_4_DIGITS=$(echo $COMMIT_HASH | cut -c 1-4)
          echo "LAST_4_DIGITS=$LAST_4_DIGITS" >> $GITHUB_ENV
      - name: Building the image
        run: |
          ls -altr
          docker build -t ${IMAGE_NAME}:${LAST_4_DIGITS} .
      - name: Login to Docker Hub
        run: docker login --username 80552 --password ${{ secrets.DOCKER_PASSWORD }}
      - name: Pushing it to the docker registry
        run: |
          docker tag ${IMAGE_NAME}:${LAST_4_DIGITS} 80552/${IMAGE_NAME}:${LAST_4_DIGITS}
          docker push 80552/${IMAGE_NAME}:${LAST_4_DIGITS}
          
          
          
          

